export const data = [
    {   id:1,
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },
    {   id:2,
        name: "Bourgogne Rouge1",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },{
        name: "Bourgogne Rouge",
        producer: "Domaine Ramonet",
        year: 2019,        
        retailPriceIncludingVat: "820,00",
        number: 11,
        retailPriceIncludingVat1: "820,00",
    },

]