export const data = [
    {
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },
    {
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },{
        name: "Ahrweiler Forstberg Spätburgunder",
        email: "ahrweiler@gmail.com",
        year: 2017,
        producer: "Julia Bertram",
        barcode: 4260485220027,
        category: "Rødvin => Tyskland => Ahr",
        costPriceEgVat: 414.20,
        dealerPriceExVAT: 458.92,
        retailPriceIncludingVAT: 1043.00,
        inventoryBalance: 3
    },
];